---
- name: "Building SR Performance Management Configuration"
  template: src={{ os }}/sr-pm.j2 dest={{ baseconfdir.path }}/08_SR-PM.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - sr-mpls