id: 204
os: iosxr
ansible_password: cisco123
napalm_driver: iosxr_netconf
xr_7: true
dnx: false
management_int: 0/RP0/CPU0/0
max_sid_depth: 8
asn: 400805
bgp_rrc: false
bgp_rr: false
netflow: false
cwdg_traffic: false
xrd: false

optics:
  - {enable: false}

network_interfaces:
  - {name: FourHundredGigE0/0/0/0, descr: "DISNEY - WC2-03", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 100, te_metric: 120, ipv4: 10.203.204.1, mask: 255.255.255.254, ipv6: '10:100:101:0/127', mtu: 9000}
  - {name: FourHundredGigE0/0/0/1, descr: "DISNEY - WC2-02", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 100, te_metric: 120, ipv4: 10.202.204.1, mask: 255.255.255.254, ipv6: '10:100:101:0/127', mtu: 9000}
  - {name: FourHundredGigE0/0/0/2, descr: "DISNEY - WC1-04", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 100, te_metric: 120, ipv4: 10.104.204.1, mask: 255.255.255.254, ipv6: '10:100:101:0/127', mtu: 9000}
  - {name: FourHundredGigE0/0/0/5, descr: "DISNEY - RR2-EAST", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 1000, te_metric: 120, ipv4: 10.204.54.1, mask: 255.255.255.254, ipv6: '10:100:101:0/127', mtu: 9000}
  - {name: FourHundredGigE0/0/0/10, descr: "DISNEY - WE2.DC2", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 1000, te_metric: 120, ipv4: 10.204.64.1, mask: 255.255.255.254, ipv6: '10:100:101:0/127', mtu: 9000}


Flex_Algo_Membership: {129, 130}

bfd_multipath:
  - {enable: true, location: 0/RP0/CPU0 }

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

ebgp_peers:
  - { enable: false }

route_reflectors:
  - ip: 1.1.1.51
    v6: 50:50:50::50
  - ip: 1.1.1.52
    v6: 51:51:51::51

sr_pce:
  - ip: 1.1.1.51
    v6: 50:50:50::50
    precedence: 1
  - ip: 1.1.1.52
    v6: 51:51:51::51
    precedence: 2

mpls_te_tunnels:
  - {enable: false}

