id: 62
os: iosxr
ansible_password: cisco123
napalm_driver: iosxr_netconf
xr_7: true
dnx: false
management_int: 0/RP0/CPU0/0
max_sid_depth: 6
asn: 400805
bgp_rrc: true
bgp_rr: false
netflow: false
xrd: true

optics:
  - {enable: false}

network_interfaces:
  - {name: GigabitEthernet0/0/0/0, descr: "WC1-03", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 1000, te_metric: 120, ipv4: 10.103.62.0, mask: 255.255.255.254, ipv6: '10:20:50:1/127', mtu: 9000}
  - {name: GigabitEthernet0/0/0/1, descr: "WC2-03", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 1000, te_metric: 120, ipv4: 10.203.62.0, mask: 255.255.255.254, ipv6: '10:20:50:1/127', mtu: 9000}
  - {name: GigabitEthernet0/0/0/2, descr: "WE1.DC1", vlan: 0, unnumbered: false, igp_inst: DISNEY_LAB, color: RED, igp_metric: 10, te_metric: 120, ipv4: 10.61.62.1, mask: 255.255.255.254, ipv6: '10:20:50:1/127', mtu: 9000}


Flex_Algo_Membership: {128, 129, 130}

bfd_multipath:
  - {enable: true, location: 0/0/CPU0 }

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

ebgp_peers:
  - { enable: false }



sr_pce:
  - ip: 1.1.1.53
    v6: 53:53:53::53
    precedence: 1
  - ip: 1.1.1.54
    v6: 54:54:54::54
    precedence: 2

route_reflectors:
  - ip: 1.1.1.53
    v6: 53:53:53::53
    precedence: 1
  - ip: 1.1.1.54
    v6: 54:54:54::54
    precedence: 2


sr_policy:
  manual:
    - { name: TEST_SR_POLICY, color: 100, endpoint: 1.1.1.64, metric_type: igp, pce: false }
  odn:
    - { color: 128, metric_type: igp, pce: false, algo: 128 }
    - { color: 129, metric_type: igp, pce: false, algo: 129 }
    - { color: 130, metric_type: latency, pce: false, algo: 130 }



multicast:
  msdp_peers:
    - {ip: 10.61.55.1, connect_source: Loopback100, vrf: UNIFIED, mesh_group: DEET_DS }
    - {ip: 10.63.55.1, connect_source: Loopback100, vrf: UNIFIED, mesh_group: DEET_DS }
    - {ip: 10.64.55.1, connect_source: Loopback100, vrf: UNIFIED, mesh_group: DEET_DS }

services:
  l3_interfaces:
#  - {name: TenGigE0/0/0/0, descr: "Internet Traffic interface", vlan: 1111, ipv4: 11.11.11.1/24, ipv6: '11:11:11:0/127', mtu: 9192}
    - {name: Loopback100, descr: "DISNEY UNIFIED VRF INTERFACE", vlan: 0, ipv4: 10.62.55.1/32, ipv6: '10:62:55:1/128'}
    - {name: Loopback101, descr: "DISNEY UNIFIED VRF INTERFACE", vlan: 0, ipv4: 10.62.56.1/32, ipv6: '10:62:56:1/128'}
    - {name: Loopback102, descr: "DISNEY UNIFIED VRF INTERFACE", vlan: 0, ipv4: 10.62.57.1/32, ipv6: '10:62:57:1/128'}
    - {name: Loopback128, descr: "DISNEY TEST BLUE VRF INTERFACE", vlan: 0, ipv4: 10.62.128.1/32, ipv6: '10:62:128:1/128'}
    - {name: Loopback129, descr: "DISNEY TEST RED VRF INTERFACE", vlan: 0, ipv4: 10.62.129.1/32, ipv6: '10:62:129:1/128'}

  evpn_vpws:
#    - { name: evpn_vpws_10_14, interface: TenGigE0/0/0/0.1000, evi: 1000 }

  l3vpn:
    - name: UNIFIED
      rd: 65111:111
      vpn_id: 111
      algo_map: ALGO-DELAY 
      interfaces: 
        - { name: Loopback110 }
      bgp_neighbors:
        - { enable: false }

    - name: CONTENT_VOD_ORIGIN
      rd: 65112:112
      vpn_id: 112
      interfaces: 
        - { name: Loopback101 }
      bgp_neighbors:
        - { enable: false }

    - name: CONTENT_VOD_SECURE
      rd: 65112:113
      vpn_id: 113
      interfaces: 
        - { name: Loopback102 }
      bgp_neighbors:
        - { enable: false }

    - name: BLUE
      rd: 65128:128
      vpn_id: 128
      algo_map: ALGO-BLUE 
      interfaces: 
        - { name: Loopback128 }
      bgp_neighbors:
        - { enable: false }

    - name: RED
      rd: 65129:129
      vpn_id: 129
      algo_map: ALGO-RED 
      interfaces: 
        - { name: Loopback129 }
      bgp_neighbors:
        - { enable: false }