---
all:
  children:
    ProviderEdge:
      hosts:
        PE.21:
          ansible_host: 198.18.130.21
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        PE.22:
          ansible_host: 198.18.130.22
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        PE.23:
          ansible_host: 198.18.130.23
          ansible_user: admin
          ansible_pass: cisco123
        PE.24:
          ansible_host: 198.18.130.24
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
    CustomerEdge:
      hosts:
        CE.11:
          ansible_host: 198.18.130.11
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        CE.12:
          ansible_host: 198.18.130.12
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        CE.13:
          ansible_host: 198.18.130.13
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        CE.14:
          ansible_host: 198.18.130.14
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr 
    Core:
      hosts:
        CORE.101:
          ansible_host: 198.18.130.101
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        CORE.102:
          ansible_host: 198.18.130.102
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        CORE.103:
          ansible_host: 198.18.130.103
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        CORE.104:
          ansible_host: 198.18.130.104
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
    PCE:
      hosts:
        vRR-SR-PCE.51:
          ansible_host: 198.18.130.51
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        vRR-SR-PCE.52:
          ansible_host: 198.18.130.52
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
    VRR:
      hosts:
        vRR-SR-PCE.51:
          ansible_host: 198.18.130.51
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
        vRR-SR-PCE.52:
          ansible_host: 198.18.130.52
          ansible_user: admin
          ansible_pass: cisco123
          ansible_network_os: cisco.iosxr.iosxr
