---
- name: "Building SR-MPLS Configuration"
  template: src={{ os }}/SR-TE.j2 dest={{ baseconfdir.path }}/07_SR-TE.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - sr-mpls