- port_limit    : 2
  version       : 2
  low_end       : true
  interfaces    : ["eth1", "eth2"]
  stack         : linux_based
  port_info     :  # set eh mac addr
                 - ip         : 172.100.0.2
                   default_gw : 172.100.0.1
                 - ip         : 172.200.0.2
                   default_gw : 172.200.0.1