---
- name: "Building Model Driven Telemetry Configuration"
  template: src={{ os }}/mdt.j2 dest={{ baseconfdir.path }}/07_mdt.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - fabric
