---
- name: "Building IGP Configuration"
  template: src={{ os }}/IGP.j2 dest={{ baseconfdir.path }}/03_IGP.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - fabric
