---
- name: "Building configuration from baseconf role"
  template: src={{ os }}/baseconf.j2 dest={{ baseconfdir.path }}/00_baseconf.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - fabric